version: '3.2'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/dist/backend/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - "internal"
  nginx:
    build:
      context: .
      dockerfile: ./docker/dist/nginx/Dockerfile
    restart: always
    depends_on:
      - "backend"
    links:
      - "backend"
    ports:
      - "8080:80"
    networks:
      - "internal"
networks:
  internal:
